export enum Screen {
  Home = 'Home',
  Services = 'Services',
  ScheduleNew = 'ScheduleNew',
  ScheduleTimeOptions = 'ScheduleTimeOptions',
  ScheduleServices = 'ScheduleServices',
  ScheduleAddresses = 'ScheduleAddresses',
  ScheduleAddressesCreate = 'ScheduleAddressesCreate',
  ScheduleAddressesUpdate = 'ScheduleAddressesUpdate',
  SchedulePayment = 'SchedulePayment',
  ScheduleSummary = 'ScheduleSummary',
  ScheduleComplete = 'ScheduleComplete',
  Schedules = 'Schedules',
  Auth = 'Auth',
  AuthEmail = 'AuthEmail',
  AuthRegister = 'AuthRegister',
  AuthLogin = 'AuthLogin',
  AuthForget = 'AuthForget',
  Profile = 'Profile',
  ChangePassword = 'ChangePassword',
  ChangePhoto = 'ChangePhoto',
}

export const Screens = {
  [Screen.Home]: undefined,
  [Screen.Services]: undefined,
  [Screen.ScheduleNew]: undefined,
  [Screen.ScheduleTimeOptions]: undefined,
  [Screen.ScheduleServices]: undefined,
  [Screen.ScheduleAddresses]: undefined,  
  [Screen.ScheduleAddressesCreate]: undefined,  
  [Screen.ScheduleAddressesUpdate]: { id: 0, },  
  [Screen.SchedulePayment]: undefined,  
  [Screen.ScheduleSummary]: undefined,
  [Screen.ScheduleComplete]: undefined,
  [Screen.Schedules]: undefined,
  [Screen.Auth]: undefined,
  [Screen.AuthEmail]: undefined,
  [Screen.AuthRegister]: undefined,
  [Screen.AuthLogin]: undefined,
  [Screen.AuthForget]: undefined,
  [Screen.Profile]: undefined,
  [Screen.ChangePassword]: undefined,
  [Screen.ChangePhoto]: undefined,
};
